default_platform(:ios)

platform :ios do
    desc "Build and Release the iOS application"
    lane :build do
        app_store_connect_api_key(
            key_id: ENV["APPLE_KEY_ID"],
            issuer_id: ENV["APPLE_ISSUER_ID"],
            key_content: ENV["APPLE_KEY_CONTENT"],
            is_key_content_base64: true,
            in_house: false #boolean value if team is Enterprise or not
        )
        
        match(
            git_url: "git@github.com:appsandreas/fastlane_sert_ios.git",
            type: "appstore"
        )

        increment_build_number

        gym(
            scheme: ENV["APP_SCHEME"],
            export_method: "app-store"
        )
        
        #upload_to_app_store(
        #    skip_metadata: true, # Пропустить загрузку метаданных
        #    skip_screenshots: true, # Пропустить загрузку скриншотов
        #    force: true # Пропустить подтверждение перед загрузкой
        #)
    end
end
