default_platform(:ios)

platform :ios do
    desc "Build and Release the iOS application"
    lane :build do
        if is_ci
          create_keychain(
            name: ENV['MATCH_KEYCHAIN_NAME'],
            password: ENV["MATCH_KEYCHAIN_PASSWORD"],
            default_keychain: true,
            unlock: true,
            timeout: 3600,
            lock_when_sleeps: false
          )
        end

        app_store_connect_api_key(
            key_id: ENV["APPLE_KEY_ID"],
            issuer_id: ENV["APPLE_ISSUER_ID"],
            key_content: ENV["APPLE_KEY_CONTENT"],
            is_key_content_base64: true,
            in_house: false #boolean value if team is Enterprise or not
        )
        
        match(
            git_url: "git@github.com:appsandreas/fastlane_sert_ios.git",
            type: "appstore",
            readonly: is_ci,
            keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
            keychain_password: ENV["MATCH_KEYCHAIN_PASSWORD"]
        )

        cocoapods

        increment_build_number

        gym(
            export_method: "app-store",
            xcargs: "-allowProvisioningUpdates"
        )
    end
end
