default_platform(:ios)

platform :ios do
    desc "Build and Release the iOS application"
    lane :build do
        setup_ci if ENV['CI']

        app_store_connect_api_key(
            key_id: ENV["APPLE_KEY_ID"],
            issuer_id: ENV["APPLE_ISSUER_ID"],
            key_content: ENV["APPLE_KEY_CONTENT"],
            is_key_content_base64: true,
            in_house: false #boolean value if team is Enterprise or not
        )
        
        match(
            force_for_new_devices: true,
            git_url: "git@github.com:appsandreas/fastlane_sert_ios.git",
            type: "appstore"
        )

        xcodeproj_path = sh("find . -depth -name '*.xcodeproj' | head -1").strip
        
        # Получение пути к профилю подписи
        profile_path = lane_context[SharedValues::SIGH_PROFILE_PATH]
        
        # Обновление проекта с новым профилем
        update_project_provisioning(
        xcodeproj: xcodeproj_path, # Динамически определенный путь к Xcode проекту
        profile: profile_path, # Путь к загруженному профилю подписи
        target_filter: '.*', # Фильтр целей проекта, к которым будет применена подпись
        build_configuration: 'Release' # Настройка сборки, для которой будет использоваться профиль
        )

        cocoapods(
          clean_install: true,
        )

        increment_build_number

        gym(
            clean: true,
            scheme: ENV["APP_SCHEME"],
            export_method: "app-store",
            export_xcargs: "-allowProvisioningUpdates"
        )
        
        upload_to_app_store(
            skip_metadata: true, # Пропустить загрузку метаданных
            skip_screenshots: true, # Пропустить загрузку скриншотов
            force: true # Пропустить подтверждение перед загрузкой
        )
    end
end
